### ISSUE TITLE
Fetch farm stellar address if set

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/grid_proxy_server#13]
- [x] add event to graphql mappings (done in https://github.com/threefoldtech/tfchain/commit/6695db7945b718d001fdcaf5edd5fdcc8514e335)
- [x] extract field for farm in grid proxy server

**Comment by DylanVerstraete** [comment]
field is `stellarAddress` under Farm object on graphql

**Comment by MohamedElmdary** [comment]
After checking out the gql api I i couldn't find `stellarAddress` field under Farm type

![Screenshot from 2021-09-14 10-33-44](https://user-images.githubusercontent.com/31689104/133224294-159e5a9f-8237-450f-a09e-354765381018.png)

**Comment by DylanVerstraete** [comment]
Will need to be added once our new devnet is live
