### ISSUE TITLE
leaking connections to rmb

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/grid_proxy_server#5]
https://github.com/threefoldtech/grid_proxy_server/blob/352e0e19ec33855f530f4b8d9e2ef3e47c752477/explorer/server.go#L143

A single RMB connection holds a redis pool. hence it's totally safe (and encouraged) to hold a reference to a single RMB connection and then use it from everywhere. But now this will just keep creating a new pool with each new request.

**Comment by waleedhammam** [comment]
fixed at: b39d0fea8799b24ed9c6fdcfcbf11f6466720269
